import z from 'zod';
import { MatchState, SocialPlatform } from './types';

/**
 * Zod schema for remote functions that take matches as arguments.
 *
 * Importantly, this does not include the `groupId`, `divisionId` field or structural fields
 * such as `round` or `nextMatchId` because those should not be freely editable by clients
 * and instead generated by the server and stored immutably.
 */
export const matchSchema = z.object({
	id: z.uuid(),
	rosterAId: z.string().nullish(),
	rosterBId: z.string().nullish(),
	teamAScore: z.int().default(0),
	teamBScore: z.int().default(0),
	draws: z.int().default(0),
	teamANote: z.string().nullish(),
	teamBNote: z.string().nullish(),
	state: z.enum(MatchState).default(MatchState.SCHEDULED),
	vodUrl: z.url().nullish(),
	scheduledAt: z.date().nullish(),
	playedAt: z.date().nullish()
});

export const socialSchema = z.object({
	platform: z.enum(SocialPlatform),
	url: z.url()
});

export const matchQueryParamsSchema = z.object({
	rosterId: z.uuid().optional(),
	divisionId: z.uuid().optional(),
	seasonId: z.uuid().optional(),
	state: z.array(z.enum(MatchState)).optional(),
	isBracket: z.boolean().optional(),
	includeEmpty: z.boolean().default(false),
	page: z.number().min(0).default(0),
	pageSize: z.number().min(1).optional()
});
