import { AuthRole } from '$lib/authRole.js';
import { roleGuard } from '$lib/remote/auth.remote.js';
import { queryMatches } from '$lib/remote/match.remote.js';
import { matchSchema } from '$lib/schemas.js';
import { db, schema } from '$lib/server/db.js';
import { parseMatchQueryParams } from '$lib/util';
import { error, json, redirect } from '@sveltejs/kit';
import z from 'zod';

export const GET = async ({ url }) => {
	const params = parseMatchQueryParams(url.searchParams);
	const matches = await queryMatches(params);
	return json(matches);
};

const createMatchSchema = matchSchema
	.omit({
		// The match ID is generated by the database, we don't want clients to provide it themselves.
		id: true
	})
	.extend({
		groupId: z.uuid()
	});

export const POST = async ({ request }) => {
	await roleGuard(AuthRole.MODERATOR);

	const body = await request.json();
	const parsedBody = createMatchSchema.safeParse(body);
	if (!parsedBody.success) {
		throw error(400, 'Invalid request body');
	}

	const [{ id }] = await db.insert(schema.match).values(parsedBody.data).returning({
		id: schema.match.id
	});

	return redirect(303, `/api/match/${id}`);
};
